volumes:
  timetable-postgres-vol:
  timetable-pgadmin-vol:

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - timetable-postgres-vol:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 82:80
    volumes:
      - timetable-pgadmin-vol:/var/lib/pgadmin
    depends_on:
      - postgres


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/postgres
      KC_DB_USERNAME: ${POSTGRES_USERNAME}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 9090:8080
    depends_on:
      - postgres
    command:
      - start-dev




  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - "nginx_vol:/etc/nginx/conf.d/"
  #     - "certbot_vol:/var/www/certbot/"
  #     - "certbot_vol:/etc/nginx/ssl/"
  #   container_name: nginx
  #   depends_on:
  #   ports:
  #     - "80:80"
  #     - "443:443"

  # certbot:
  #   image: certbot/certbot:latest
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - "certbot_vol:/var/www/certbot/"
  #     - "certbot_vol:/etc/letsencrypt/"
  #     - "certbot_vol:/var/lib/letsencrypt/"