volumes:
  postgres_vol:

services:

  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    ports:
      - "54321:5432"

    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - 9090:8080
    command:
      - start-dev

  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - "nginx_vol:/etc/nginx/conf.d/"
  #     - "certbot_vol:/var/www/certbot/"
  #     - "certbot_vol:/etc/nginx/ssl/"
  #   container_name: nginx
  #   depends_on:
  #   ports:
  #     - "80:80"
  #     - "443:443"

  # certbot:
  #   image: certbot/certbot:latest
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - "certbot_vol:/var/www/certbot/"
  #     - "certbot_vol:/etc/letsencrypt/"
  #     - "certbot_vol:/var/lib/letsencrypt/"