name: timetable

volumes:
  postgres-vol:
  nginx-conf-vol:
  certbot-vol:


services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: timetable-postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: ${KEYCLOAK_DB}
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HTTP_RELATIVE_PATH: ${KEYCLOAK_HTTP_RELATIVE_PATH}
      KC_PROXY: ${KEYCLOAK_PROXY}
      KC_HOSTNAME_STRICT: ${KEYCLOAK_HOSTNAME_STRICT}
    depends_on:
      - postgres
    command:
      - start

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: timetable-nginx
    volumes:
      - "nginx-conf-vol:/etc/nginx/conf.d/"
      - "certbot-vol:/var/www/certbot/"
      - "certbot-vol:/etc/nginx/ssl/"
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:v2.8.0
    volumes:
      - "certbot-vol:/var/www/certbot/"
      - "certbot-vol:/etc/letsencrypt/"
      - "certbot-vol:/var/lib/letsencrypt/"
    depends_on:
      - nginx
  # frontend:
  #   build:
  #     context: ./../client-side/timetable-next
  #     dockerfile: Dockerfile
  #   image: timetable-next
  #   depends_on:
  #     - nginx
